# Generated by Django 3.2 on 2022-06-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='DEFAULT VALUE', max_length=30),
        ),
    ]
