# Generated by Django 3.2 on 2022-06-05 13:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220605_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='post',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
